- .gitignore
- backend/.eslintignore
- backend/.eslintrc
- backend/nodemon.json
- backend/package-lock.json
- backend/package.json
- backend/src/index.ts
- backend/tsconfig.json
> Backend setup

- frontend/.eslintrc.json
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.tsx
- frontend/src/index.tsx
Es werden die Formatierungs-Einstellungen von airbnb verwendet
> Frontend EsLint installiert und eingerichtet

- Dockerfile
- backend/src/index.ts
- backend/src/util/filesystem/path-exists.ts
- build.sh
- frontend/yarn.lock
Zudem im backend prüfen, ob der client exportiert wurde.
> Projekt in docker image verpacken.

- .github/workflows/docker-build-test.yml
Nach merge muss geprüft werden, ob das die CD funktioniert. Dazu bitte schauen, ob unter https://hub.docker.com/r/digitalisierungatschool/test ein image liegt.
> docker-build workflow fürs Testsystem hinzufügen

- frontend/src/components/HomeSelcetion/ModulCollection.tsx
- frontend/src/components/ModulSelectionComponent/SelectionComponent.css
Den Modultext bissl kleiner gemacht, und den margin angepasst, so sollte die schrift nicht mehr unter den button rutschen
> kleine_Anpassungen

- frontend/src/components/Toolbar/LoginLogoutButton/LoginLogoutButton.css
- frontend/src/components/Toolbar/LoginLogoutButton/LoginLogoutButton.tsx
- frontend/src/components/Toolbar/Toolbar.css
- statt px -> vw verwendet
- Text des Login-Button größer gemacht
> Toolbar CSS-Anpassungen, für größere Bildschirme

- frontend/src/components/HomeSelcetion/ModulCollection.tsx
- frontend/src/components/ModulSelectionComponent/SelectionComponent.css
- frontend/src/components/ModulSelectionComponent/SelectionComponent.tsx
Die Auswahlkomponente vom Startbildschirm wurde nun so angepasst, das es auch auf einem 4K Bildschirm passt.
> Start_Komponente_Angepasst

- frontend/src/components/FifthExamComponent/FifthExamFormComponent.css
- frontend/src/components/FifthExamComponent/FifthExamFormComponent.tsx
- frontend/src/pages/PruefungskomponenteEntryPage.tsx
neuer brach aufgrund von merge konflickten mit modulen
> Fifth exam component page 2

- frontend/src/components/HomeSelcetion/ModulCollection.tsx
Die Route für die SelectionComponent auf der Homepage hatten nicht gestimmt. Sind jetzt angepasst und es funktioniert
> Überarbeitet

- Dockerfile
build fixen
Dockerfile:
python installieren
> #2-datenbank-aufsetzen-und-anbinden doku update

- .gitignore
- backend/database.json
- backend/src/db/dbAccessor.ts
- build.sh
- docker-compose-prod.yml
- docker-compose-test.yml
dazu muss die db im data ordner liegen
und die database.json & der migrations ordner müssen mit ins image gepackt werden
> #37-db-migrate-up-in-docker-compose-ausführen

- frontend/src/Theming.tsx
- frontend/src/index.tsx
Erstmal bei den meisten den Default beibehalten. Farben können ja noch geklärt werden
> Material UI Theming aufgesetzt

- frontend/src/APIRequestFunction.tsx
- frontend/src/components/HomeSelcetion/ModulCollection.tsx
- frontend/src/components/Toolbar/Toolbar.tsx
- frontend/src/reducer/authReducer.tsx
Startseite, Toolbar für Admins angepasst
> Kleine Änderung in ApiRequestFunction,

- frontend/src/components/Buttons/CreateCSVButton.tsx
- frontend/src/components/FifthExamAdminTable/FifthExamAdminTable.tsx
- frontend/src/components/FifthExamComponent/FifthExamFormComponent.tsx
- frontend/src/components/Toolbar/LoginLogoutButton/LoginLogoutButton.tsx
- frontend/src/pages/admin/AdminPruefungskomponentePage.css
- frontend/src/pages/admin/AdminPruefungskomponentePage.tsx
- frontend/src/pages/admin/SettingsPage.tsx
> 5 pk uebersicht v2

- frontend/src/index.tsx
Ursache: falscher import des ThemeProviders
> Bugfix: keine Rahmen um die Textfelder

- frontend/src/components/FifthExamAdminTable/FifthExamAdminTable.tsx
> 5 pk admin fix

- backend/src/auth/sso.ts
- backend/src/auth/staticAuthStrings.ts
- backend/src/db/user.ts
- backend/src/routing/controllers/Auth.ts
- backend/types/sso/interfaces.d.ts
- interfaces für sso-Typen in separate Datei geschrieben
- nach Login auf Homepage weiterleiten
> Neue Nutzer der DB hinzufügen, existierende Nutzer aktualisieren

- backend/src/routing/controllers/Auth.ts
- backend/src/routing/routes/auth.ts
- erreichbar über '/auth/logout/sso'
> iServ-Logout implementiert

- backend/src/auth/sso.ts
- backend/src/auth/staticAuthStrings.ts
- backend/src/db/user.ts
- backend/src/routing/controllers/Auth.ts
- backend/src/routing/routes/auth.ts
- in callback auf '/' weiterleiten
- Gruppen in separater Funktion zu Array umwandeln
> Rollenabfrage vor Schnittstelle korrigiert/erweitert

- backend/migrations/20211201152520-facharbeit-testdaten.js
- backend/migrations/sqls/20211201152520-facharbeit-testdaten-down.sql
- backend/migrations/sqls/20211201152520-facharbeit-testdaten-up.sql
- backend/package-lock.json
- backend/package.json
- backend/src/index.ts
- backend/src/routing/controllers/api/Facharbeit.ts
- backend/src/routing/routes/api/facharbeit.ts
- backend/src/routing/validators/api/facharbeit.ts
- dokumentation/db/Kant-Schnittstellen.txt
Schnittstelle umgesetzt.
Fehlformatierte Testdaten entfernt.
> Schnittstelle api/facharbeit/uploadDocument (POST)

- backend/src/auth/staticAuthStrings.ts
- backend/src/routing/controllers/Auth.ts
- nach callback auf Startseite weiterleiten (auch bei Fehler)
> Logout in try-catch-Block eingebettet
